"""init

Revision ID: aa9cbd2759c4
Revises: effc947fa7f7
Create Date: 2023-12-11 19:20:45.370996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9cbd2759c4'
down_revision: Union[str, None] = 'effc947fa7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemons', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemons', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
